Intake_Radiology_Notes_Task:
  description: >
    Receive raw written or dictated notes from the radiologist: {raw_note}
    Clean and prepare them for downstream processing.
  agent: input_agent
  expected_output: >
    Cleaned and standardized version of the following note: {raw_note}
    Ready for transcription or parsing.

#Transcribe_Audio_Input_Task:
  #description: >
    #Convert spoken radiology notes into well-formatted text using speech-to-text, preserving medical language and intent.
  #agent: transcriber_agent
  #expected_output: >
    #Accurate, punctuation-aware text transcription of the dictated input.
  #optional: true

Parse_Clinical_Sections_Task:
  description: >
    Parse the intake text into five standard sections: Titre, Indication, Technique, Resultat, and Conclusion.
  agent: parser_agent
  dependent_tasks: [Intake Radiology Notes]
  expected_output: >
    Structured content with clearly defined Indication, Technique, Résultat, and Conclusion sections.

Validate_Medical_Consistency_Task:
  description: >
    Ensure the parsed content contains no contradictions or missing key clinical information. Flag and request clarifications if necessary.
  agent: validator_agent
  dependent_tasks: [Parse Clinical Sections]
  expected_output: >
    A validated version of the structured content with issues flagged or resolved.

Format_Report_to_Template_Task:
  description: >
    Format the validated content into the standardized .docx radiology report template for output.
  agent: formatter_agent
  dependent_tasks: [Validate Medical Consistency]
  expected_output: >
    A formatted report structure compliant with the radiology report template.

Generate_Final_Report_Task:
  description: >
    Finalize the report with polished language, ensure clarity, and prepare it for export to the user or EHR system.
  agent: writer_agent
  dependent_tasks: [Format Report to Template]
  expected_output: >
    A finalized, clear, and grammatically correct radiology report ready for delivery.
  output_format: .docx
  output_file: report.docx
